name: Test WordPress Docker Environment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        wordpress-version: ['6.8', 'latest']
        php-version: ['8.1', '8.2', '8.3']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        cp .env.example .env
        # Use test credentials
        sed -i 's/change_this_secure_root_password/test_root_pass/g' .env
        sed -i 's/change_this_secure_password/test_wp_pass/g' .env
        sed -i 's/change_this_admin_password/test_admin_pass/g' .env
    
    - name: Start Docker environment
      run: |
        docker compose up -d
        
    - name: Wait for services to be ready
      run: |
        timeout 120 bash -c 'until docker compose exec -T db mariadb -u root -ptest_root_pass -e "SELECT 1"; do sleep 5; done'
        timeout 120 bash -c 'until curl -f http://localhost:8000; do sleep 5; done'
    
    - name: Test Composer script
      run: |
        chmod +x composer.sh
        ./composer.sh doctor
        ./composer.sh install
        ./composer.sh show
    
    - name: Test plugin management
      run: |
        ./composer.sh plugin install hello-dolly
        ./composer.sh plugin list | grep hello-dolly
        ./composer.sh plugin remove hello-dolly
    
    - name: Test theme management
      run: |
        ./composer.sh theme list
        ./composer.sh theme install twentytwentythree
        ./composer.sh theme list | grep twentytwentythree
    
    - name: Test WordPress CLI
      run: |
        ./composer.sh wp core version
        ./composer.sh wp plugin list
        ./composer.sh wp theme list
    
    - name: Validate Composer
      run: |
        ./composer.sh validate
    
    - name: Check for security vulnerabilities
      run: |
        ./composer.sh outdated || true
    
    - name: Test cleanup
      run: |
        docker compose down -v
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: docker-logs-${{ matrix.wordpress-version }}-${{ matrix.php-version }}
        path: |
          /tmp/docker-compose-logs.txt